spring:
  application:
    name: test
#  cloud:
#    nacos:
#      discovery:
#        username: nacos
#        password: nacos
#        namespace: 5d9179d9-85b1-483d-a55a-a62a3732b4c4
#        server-addr: localhost:8848
server:
  port: 8004
